server:
    port: 9997
    
spring:
  application:
      name: api-configserver

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jonavcar/Proyecto2_ConfigData
          searchPaths: application-config
          default-label: main
          username: jonavcar@gmail.com
          password: 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
